client/src/components/Welcome.jsx
Solamente creé un componente: Welcome.jsx
=> Commit de prueba

api/index.js, api/src/app.js, api/src/db.js, api/src/models/User.js, api/src/routes/index.js
Deja la misma estructura que la que usamos en el PI, cree el modelo User.js solo como ejemplo por que me rompía si estaba vacío siéntanse libres de modificarlo Guillermo y Tomas. Recuerden agregar un archivo .env en api con sus datos correspondientes
DB_USER=
DB_PASSWORD=
DB_HOST=localhost:5432
ya les debería servir npm start si lo hacen en la carpeta api, el servidor corre en el puerto 3001
=> nodemon working, added the basic structure (copy PI)

README.md
empece a crear el readme, basicamente puse las nociones basicas del juego y los valores de la carta.
hice el push en main, porque en teoria esto no deberia modificar nada de la app. si esta mal lo cambio a rama dev
=> mejorando readme

api/package-lock.json, api/src/models/Message.js, api/src/models/User.js
Mejorado modelo User, creado modelo Message.
=> Guille dbmodels

client/src/Redux/actions-types/index.js, client/src/Redux/actions-types/signUpUserActions.js, client/src/Redux/actions/index.js, client/src/Redux/reducer/index.js, client/src/Redux/reducer/signUpReducer.js, client/src/components/SignUp.jsx
Eso, cree un combine reducer para poder trabajar mas tranquilos, así cada uno va creando los reducers por separado y evitamos pisarnos
=> creacion del combine reducer, cambio en archivos

api/src/routes/user.js
Cree todas las rutas de /user que están en el documento.
Para poderlas probar cuando ya esta la base de datos por ahora las deje comentadas seguro pueden existir errores o cosas que rompan o que implemente mal, pero la idea es que cuando ya esta la base de datos, ir probando una por una que funcione correctamente e ir corrigiendo.
=> All Routes get  user in google doc

api/index.js, api/src/db.js, api/src/models/Message.js, api/src/models/User.js, api/src/routes/fillTable.js, api/src/routes/index.js, api/src/routes/user.js
Trabajando en archivos de base de datos. cambiosn en archivo db.js fueron necesarios para testeos. Agregado archivo "filltables" enrutas api. mejorrado rutas de user.
La ruta POST api/filltables llena usuarios como ejemplo.
=> Guille api routes2

api/src/db.js, api/src/models/Friends.js
=> Creacion Friends associative entity

api/src/models/Games.js, api/src/models/User.js, api/src/routes/fillTable.js, api/src/routes/user.js
Agregada otras rutas de backend.
=> Agregada funcionalidad de POST y GET de usuarios. 

api/src/routes/friends.js
- implementacion put y post para los request de amistad entre usuarios
- se modifico el archivo friends.js de la carpeta routes
=> routes api/friend

api/index.js, api/package-lock.json, api/package.json, api/src/db.js, api/src/models/Games.js, api/src/routes/fillTable.js, api/src/routes/friends.js, api/src/routes/user.js, client/.gitignore
Funcionalidad de semillero y rutas user
=> Guille rutas2

api/nodemon.json
fix nodemon, socket io, fix conflicts
=> fix nodemon

api/src/routes/user.js
=> Guille rutas user

api/index.js, api/src/routes/user.js
Agregada ruta api/user/login, que solicita un objeto con {usernameInput: ... , passwordInput:... } para hacer el login. Necesita mejorarse con aspectos de seguridad.
=> Agregada ruta api/user/login/

client/src/App.js, client/src/components/game.jsx, client/src/components/styles/game.module.css
creacion de /game para mostrar como seria la partida
=> boceto de juego agregado en /game

client/package-lock.json, client/src/App.js, client/src/Redux/actions-types/roomsActions.js, client/src/Redux/actions/index.js, client/src/Redux/reducer/roomsReducer.js, client/src/components/SignUp.jsx, client/src/components/rooms/JoinRoomForm.jsx, client/src/components/rooms/Rooms.jsx, client/src/components/rooms/RoomsList.jsx
- Ahora la página de rooms solamente muestra los rooms o el chat, dependiendo de si el jugador ya está o no dentro de uno.
- Código reestructurado de los componentes de la carpeta rooms.
- Al crear un nuevo usuario, ahora somos redireccionados a Welcome.
- A la ruta /login se le cambió el nombre por /welcome
=> Minor fixes and code restructure

client/src/components/NavBar.jsx, client/src/components/rooms/Chat.jsx, client/src/components/rooms/JoinRoomForm.jsx, client/src/components/rooms/Rooms.jsx, client/src/components/rooms/RoomsList.jsx, client/src/components/rooms/styles/JoinRoomForm.module.css, client/src/components/rooms/styles/Rooms.module.css, client/src/components/rooms/styles/RoomsList.module.css, client/src/components/styles/NavBar.module.css, client/src/components/styles/SignUp.module.css
Están terminados los estilos para la parte del /rooms.
Aún hay cosas que faltan por ser implementadas, pero requerimos de todas las conexiones terminadas.
=> "Finished: First styles in /rooms"

client/src/components/Profile.jsx
solo agregue el <> antes de navBar para que no rompiera
=> minor fix last merge

client/src/components/Landing.jsx, client/src/components/Profile.jsx, client/src/components/styles/Profile.module.css
Ya están los primeros estilos para /profile.
=> Styles for /profile

api/src/socketServer.js, api/src/socketTournaments.js, client/src/App.js, client/src/Redux/actions-types/tournamentsActions.js, client/src/Redux/actions/index.js, client/src/Redux/reducer/index.js, client/src/Redux/reducer/tournamentsReducer.js, client/src/components/tournaments/Tournaments.jsx, client/src/components/tournaments/TournamentsForm.jsx, client/src/components/tournaments/TournamentsList.jsx
He terminado las bases para la realización de torneos:
- Generación de ID
- Sockets para la conexión cliente-servidor
- Componentes esenciales
Pueden acceder a los componentes a través de /tournaments
Falta agregar un límite de usuarios para los rooms de los torneos y un sistema capaz de controlar los sucesos de las partidas del torneo.
=> Sockets for tournaments

api/src/socketServer.js, client/src/components/game.jsx, client/src/components/rooms/Chat.jsx, client/src/components/rooms/styles/Chat.module.css, client/src/components/rooms/styles/Rooms.module.css, client/src/components/styles/DeleteFriendButton.module.css, client/src/components/styles/ErrorPage.module.css, client/src/components/styles/FriendInfo.module.css, client/src/components/styles/Landing.module.css, client/src/components/styles/LogIn.module.css, client/src/components/styles/Modal.module.css, client/src/components/styles/Profile.module.css, client/src/components/styles/Ranking.module.css, client/src/components/styles/SignUp.module.css, client/src/components/styles/Welcome.module.css, client/src/components/styles/game.module.css
Mejoras juego, salvo bugs que se me pasaran de lo básico solo falta el no querer truco por que tengo una duda respecto a como funciona.
Cambio de imágenes a webp para que cargue mas rápido.
Estilos del componente juego, intento de hacerlo reactive.
=> Fix bugs logic

client/src/components/NavBar.jsx, client/src/components/Welcome.jsx, client/src/components/rooms/Rooms.jsx
Facebook funcionando bien!
usar para probar :
blackcomputacion@live.com
truco1234
=> facebook funcionando

api/src/socketGameLogic.js, api/src/socketTournaments.js, client/src/components/game.jsx, client/src/components/tournaments/TournamentGames.jsx
Funcionalidad de torneos terminada.
Al finalizar los torneos, estos arrojan un listado de los participantes con sus respectivos puntos (si es que tuvieron).
Falta manejar una llamada a la API para aumentar la cantidad de torneos ganados del respectivo jugador.
=> Tournaments ready

api/src/socketGameLogic.js, api/src/socketRooms.js, client/src/Redux/reducer/logReducer.js, client/src/components/game.jsx, client/src/components/rooms/Chat.jsx, client/src/components/rooms/JoinRoomForm.jsx, client/src/components/rooms/Rooms.jsx, client/src/components/rooms/RoomsList.jsx, client/src/components/rooms/styles/Chat.module.css, client/src/components/styles/game.module.css
Ya pueden salirse de la partida.
Ya pueden enviar solicitud de amistad a su oponente.
Correcciones varios bugs del juego.
Agregado cartel que indica turno. (bug al ganar los dos primeros donde notifica aunque termine la mano de turno al que le tocaba)
Agregado mensaje de esperando otro jugador para iniciar y jugar X se ha unido. 
Agregado botón para reportar aunque todavía no hace nada.
Agregado botón para desplegar el panel de ayuda o tutorial que andan haciendo.
Agregado botón para mostrar puntos, ahora se muestran automáticamente durante 3 segundos al haber actualización de puntos o se pueden ver con el nuevo botón (quitar haciendo click fuera del cuadro de puntos). 
Corregido bug que no mostraba el nombre del usuario durante la partida. 
Agregados varios estilos para intentar hacer la …
=> Responsive game

api/src/controller/users.js, api/src/db.js, api/src/models/Reports.js, api/src/routes/fillTable.js, api/src/routes/friends.js, api/src/routes/index.js, api/src/routes/reports.js, client/src/components/AdminPanel.jsx, client/src/components/FilaDeTabla.jsx, client/src/components/styles/AdminPanel.module.css, client/src/components/styles/FilaDeTabla.module.css
Falta lógica de frontend para agregar reportes a otros jugadores.
=> Implementada sistema de reports en backend.

api/src/routes/games.js, api/src/socketGameLogic.js, api/src/socketRooms.js, api/src/socketTournaments.js, client/src/Redux/reducer/logReducer.js, client/src/Redux/reducer/roomsReducer.js, client/src/components/GameRequest.jsx, client/src/components/Profile.jsx, client/src/components/game.jsx, client/src/components/rooms/Rooms.jsx, client/src/components/rooms/RoomsList.jsx, client/src/components/socket.js, client/src/components/tutorial/Tutorial.jsx
Agregado reporte desde el front, limite a 1 reporte por partida. 
Agregado feedback al usuario en caso de que reporte mas de una vez o invite mas de una vez por partida.
El estado de la partida es enviado al jugador y es recordado por local Storage.
Correcciones bugs del juego.
Ahora se actualiza también la información de usuario respecto a partidas jugadas, ganas y perdidas.
=> Block multiple sessions
